# 수반행렬 사용해 역행렬 구하기

In [19]:
import numpy as np

# 원하는 {row}행, {col}열을 지우고 새로운 matrix를 반환
def delete_element(matrix, row, col):
    new_matrix = np.delete(np.delete(matrix, row, axis=0), col, axis=1)
    return new_matrix
    
n = int(input("n * n Matrix; n? ")) # n 입력받기

elements = [list(map(int, input().split())) for _ in range(n)] # 행렬 성분 입력받기
matrix = np.array(elements) # 배열을 행렬로 변환

if np.linalg.det(matrix) != 0 : # detMatrix != 0 일 때만 역행렬 계산시작 
    adjMatrix = np.eye(n) # n * n 행렬 생성
    for i in range(0,n): 
        for j in range(0,n):
            adjMatrix[i][j] = np.linalg.det(delete_element(matrix, i, j)) # i행, j행 삭제한 행렬의 행렬식을 구하고 저장
            if (i+j) % 2 != 0: # 홀수일시 -1 곱함
                adjMatrix[i][j] = -adjMatrix[i][j]
    
    adjMatrix = np.array(adjMatrix) # 행렬로 변환
    adjMatrix = adjMatrix.T # 전치시킴
    inverse = (1 / np.linalg.det(matrix)) * adjMatrix # 역행렬 구하기
    
    print("\nInverse Matrix:")
    print(inverse)
    
else: # 역행렬 존재 X
    print("detMatrix = 0, Don't have inverse")

n * n Matrix; n?  3
 1 2 3
 4 5 6
  7 8 2



Inverse Matrix:
[[-1.80952381  0.95238095 -0.14285714]
 [ 1.61904762 -0.9047619   0.28571429]
 [-0.14285714  0.28571429 -0.14285714]]


# 가우스 조던 이용해 역행렬 구하기

In [20]:
# 가우스 조던을 적용할 수 있는지 체크하는 함수 : 해당 열이 모두 0이거나, 한 행이 모두 0 일 때 None을 반환함
def check_Matrix(matrix, index, num): 
    row_check = True
    col_zero_num = 0
    for i in range(index, num):
        if matrix[i][index] == 0: 
            col_zero_num += 1
            
        if all(matrix[i, :] == 0):
            row_check = False
            
    if col_zero_num == (num - index) or not row_check:
        return None
        
    return 1

# Gauss_Jordan의 계산 한 번을 해당 행렬에 적용하는 함수
def apply_Gauss_Jordan(matrix, index,num):
    # 해당 열에서 성분이 0이 아닌 첫 행을 찾고, 해당 행을 pivot_row로 설정
    for i in range(index, num):
        if matrix[i][index] != 0:
            pivot_row = i
            break

    matrix[pivot_row] = matrix[pivot_row] / matrix[pivot_row, index]  # pivot_row 행을, [pivot_row행, index열]의 성분으로 나눔(선행 1 만들기)
    matrix[[index, pivot_row]] = matrix[[pivot_row, index]]     # 해당 pivot_row를 알맞는 행으로 교환함

    for i in range(0, num):
        if matrix[i, index] != 0 and i != index: # [모든 행, index열]의 성분이 0이 아닐 때만
            matrix[i] = matrix[i] + (-matrix[i][index] * matrix[index]) # pivot_row행의 실수 배 덧셈을 통해 0으로 만듦

# Gauss_Jordan을 끝까지 수행하고 역행렬을 반환해주는 함수
def inverse_matrix(matrix, num):
    identity_matrix = np.eye(num) # num * num 단위행렬을 만듦
    augmented_matrix = np.hstack([matrix, identity_matrix]) # matrix : I 를 만듦

    # 모든 열에 대해 진행함
    for index in range(0, num): 
        # Matrix를 검사 하고 문제가 있으면 None을 반환하고 함수 종료
        if check_Matrix(augmented_matrix, index, num) is None:
            return None
        # 해당 열에 대한 연산을 실행
        apply_Gauss_Jordan(augmented_matrix, index, num) is None

    # num열 이후 (단위행렬이었던 자리)를 리턴함  
    return augmented_matrix[:, num:]

n = int(input("n * n Matrix; n? ")) # n 입력받기

elements = [list(map(int, input().split())) for _ in range(n)] # 행렬 성분 입력받기
matrix = np.array(elements) # 배열을 행렬로 변환

inverse_matrix_result = inverse_matrix(matrix, n) # 역행렬 만들기

if inverse_matrix_result is not None: # 역행렬이 존재하면 출력
    print("\nInverse Matrix:") 
    print(inverse_matrix_result)
else: # 역행렬이 없다면 에러 출력
    print("Don't have inverse.")


n * n Matrix; n?  3
 1 2 3
 4 5 6
 7 8 2



Inverse Matrix:
[[-1.80952381  0.95238095 -0.14285714]
 [ 1.61904762 -0.9047619   0.28571429]
 [-0.14285714  0.28571429 -0.14285714]]
