In [66]:
## 수반행렬 사용하여 역행렬 구하기
import numpy as np

## 원하는 행, 열을 지우고 새로운 matrix를 반환
def delete_element(matrix, row, col):
    new_matrix = np.delete(np.delete(matrix, row, axis=0), col, axis=1)
    return new_matrix
    
elements = [[1,2,3],[4,5,6],[7,8,2]]
matrix = np.array(elements)

if np.linalg.det(matrix) != 0 : # detMatrix != 0 일 때만 역행렬 계산시작 
    adjMatrix = [[0,0,0],[0,0,0],[0,0,0]]
    for i in range(0,3):
        for j in range(0,3):
            adjMatrix[i][j] = np.linalg.det(delete_element(matrix, i, j)) # i행, j행 삭제하고 행렬식을 구함
            if (i+j) % 2 != 0: # 홀수일시 -1 곱함
                adjMatrix[i][j] = -adjMatrix[i][j]
    
    adjMatrix = np.array(adjMatrix) # 행렬로 변환
    adjMatrix = adjMatrix.T # 전치시킴
    inverse = (1 / np.linalg.det(matrix)) * adjMatrix # 역행렬 구하기
    
    print("\nInverse Matrix:")
    print(inverse)
    
else: # 역행렬 존재 X
    print("detMatrix = 0, Don't have inverse")


Inverse Matrix:
[[-1.80952381  0.95238095 -0.14285714]
 [ 1.61904762 -0.9047619   0.28571429]
 [-0.14285714  0.28571429 -0.14285714]]


In [90]:
import numpy as np

def check_Gauss_Jordan(matrix, index):
    row_check = True
    col_zero_num = 0
    for i in range(0, 3):
        if matrix[i][index] == 0: 
            col_zero_num += 1
        if all(matrix[i, index:] == 0):
            row_check = False
            
    if col_zero_num == 3 or not row_check:
        return None
        
    return 1

def apply_Gauss_Jordan(matrix, index):
    pivot_row = np.argmax(np.abs(matrix[index:, index])) + index

    if matrix[pivot_row, index] == 0:
        return None  # Avoid division by zero

    matrix[[index, pivot_row], :] = matrix[[pivot_row, index], :]

    matrix[index, :] /= matrix[index, index]

    for i in range(3):
        if i != index:
            matrix[i, :] -= matrix[i, index] * matrix[index, :]

def inverse_matrix(matrix):
    identity_matrix = np.eye(3)
    augmented_matrix = np.hstack([matrix, identity_matrix])

    for index in range(0, 3):
        if check_Gauss_Jordan(augmented_matrix, index) is None or \
                apply_Gauss_Jordan(augmented_matrix, index) is None:
            return None

    return augmented_matrix[:, 3:]

elements = [[1, 2, 3], [4, 5, 6], [7, 8, 2]]
matrix = np.array(elements)

inverse_matrix_result = inverse_matrix(matrix)

if inverse_matrix_result is not None:
    print("\nInverse Matrix:")
    print(inverse_matrix_result)
else:
    print("Don't have inverse.")


Don't have inverse.
